### ISSUE TITLE
Missing currencies

### ISSUE THREAD

**Issue by eXeDK** [freeall/currency-codes#12]
It seems that currency code "933" - BYN - Belarusian ruble do not exist in your data even though it is part of ISO4217. 
Do you accept pull requests for missing currencies or are you willing to add them yourself?

Best Regards
Thomas

**Comment by freeall** [comment]
@eXeDK I can add you as a contributor and then you can add it. I'll publish it then. Sounds good?

**Comment by eXeDK** [comment]
Yes that sounds fine. It could be done using a PR as well but we can do it like this :-)
