### ISSUE TITLE
Nested dependency of axios can be a problem

### ISSUE THREAD

**Issue by fredpolicarpo** [freeall/currency-codes#33]
Hi,

First of all, thanks for being develop this library, it is very useful :claps:

I just have feedback about the dependency of  `axios`. 

In my project, I can't depend on libraries that can do network connections, due to security restrictions.

Should you separate this dependency in another project for the fetch function, and keep a static one that doesn't have this dependency?

**Comment by ronkorving** [comment]
Axios is only used to keep `data.js` uptodate. It's a devDependency so you shouldn't end up having it installed in your own project just because you use `currency-codes`.
